Models/ContactDetail.cs
namespace TBSTech.Models
{
    public class ContactDetail
    {
        public int Id { get; set; }
        public string PhoneNumber { get; set; }
        public string TelePhone { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
    }
}

Areas/Admin/Controllers/ContactDetailsController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using TBSTech.Data;
using TBSTech.Models;
using TBSTech.Repository;

namespace TBSTech.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ContactDetailsController : BaseController
    {
        private readonly IContactDetailsRepository _contactDetailsRepo;
        private readonly ApplicationDbContext _context;
        public ContactDetailsController(IToastNotification _clientNotification, ApplicationDbContext context,
         IContactDetailsRepository contactDetailsRepo) : base(_clientNotification)
        {
            _context = context;
            _contactDetailsRepo = contactDetailsRepo;
        }

        public IActionResult Index()
        {
            var data = _contactDetailsRepo.Collection();
            return View(data);
        }
        public IActionResult New()
        {
            ViewBag.Message = "New";
            var data = _context.ContactDetails.ToList().Count();
            if (data >0)
            {
                contactDetailsNotify();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [HttpPost]
        public IActionResult New(ContactDetail model, string message)
        {

            if (message.Equals("Update"))
            {
                _contactDetailsRepo.Update(model);
                updateNotify();
            }
            else if (message.Equals("New"))
            {
                _contactDetailsRepo.Insert(model);
                addNotify();
            }
            _contactDetailsRepo.Commit();

            return RedirectToAction(nameof(Index));

        }
        public IActionResult Update(int id)
        {
            ViewBag.Message = "Update";
            var data = _contactDetailsRepo.GetSingle(x => x.Id == id);
            return View(nameof(New), data);
        }
        public IActionResult Delete(int id)
        {

            var courseToDelete = _contactDetailsRepo.GetSingle(x => x.Id == id);

            _contactDetailsRepo.Delete(x => x.Id == id);
            _contactDetailsRepo.Commit();
            deleteNotify();
            return RedirectToAction(nameof(Index));
        }
    }
}

Areas/Admin/Views/ContactDetails/Index.cshtml
 @model List<TBSTech.Models.ContactDetail>
  @{
    var N=0;
}
 <!-- Content Wrapper. Contains page content -->

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Contact Details</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Your Contact Detail</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
<div class="card">
        <div class="card-header">
          <h3 class="card-title">Contact Details</h3>
                              <a asp-controller="ContactDetails" asp-action="New" style="background-color:#007bff;text-align:center;float:right;color:white;width:150px;border-radius:20px;cursor:pointer;padding:10px;">Add ContactDetails</a>

        </div>
        <div class="card-body p-0">
          <table class="table table-striped projects">
              <thead>
                  <tr>
                      <th style="width: 10%">
                         #
                      </th>
                      <th style="width: 20%">
                          Phone Number
                      </th>
                      <th style="width: 25%;">
                          Telephone
                      </th>
                      <th style="width: 20%;">
                        Address
                      </th>
                      <th style="width: 20%;">
                        E-mail
                      </th>
                    
                      <th style="width: 25%">
                      </th>
                  </tr>
              </thead>
      <!-- Default box -->
      @foreach (var item in Model)
      {
          N++;
      
      
              <tbody>
                  <tr>
                      <td>
                          @N
                      </td>
                      <td>
                           <strong>   @item.PhoneNumber</strong>
                          
                      </td>
                        <td  style="text-align:justify;">
                          <strong>
                              @item.TelePhone
                          </strong>
                      </td>
                       <td>
                           <strong>   @item.Address</strong>
                          
                      </td>
                       <td>
                           <strong>   @item.Email</strong>
                          
                      </td>
                    
                      <td>
                          <a class="btn btn-info btn-sm" asp-controller="ContactDetails" asp-action="Update" asp-route-id="@item.Id" style="margin-bottom: 5px;border-radius:0;">

                              
                             <b>+</b> Edit&nbsp;&nbsp;&nbsp;&nbsp;
                          </a>
                          <a class="btn btn-danger btn-sm" asp-controller="ContactDetails" asp-action="Delete" asp-route-id="@item.Id" style="margin-bottom: 5px;border-radius:0;">
                              
                             <b>-</b> Delete
                          </a>
                      </td>
                  </tr>
                  
              </tbody>
        
      
      }
        </table>
        </div>
   
      </div>
    </section>
    <!-- /.content -->

  <!-- /.content-wrapper -->

Areas/Admin/Views/ContactDetails/New.cshtml
@model TBSTech.Models.ContactDetail 
 <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Contact Detail</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Contact Detail</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-6">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">General</h3>

              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                  <i class="fas fa-minus"></i></button>
              </div>
            </div>
            <form method="POST" asp-action="New" asp-controller="ContactDetails" enctype="multipart/form-data"> 
            <div class="card-body">
              
              <input type="hidden" value ="@ViewBag.Message" name="message" id="message"class="form-control" />
              
              <input type="hidden" asp-for="Id">
              <div class="form-group">
                <label asp-for="PhoneNumber">Phone Number</label>
                <input type="text" asp-for="PhoneNumber" id="inputName" class="form-control">
              </div>
              <div class="form-group">
                <label asp-for="TelePhone">Telephone</label>
                <input asp-for="TelePhone" id="inputDescription" class="form-control">
              </div>
             <div class="form-group">
                <label asp-for="Address">Address</label>
                <input asp-for="Address" id="inputDescription" class="form-control" >
              </div>
             <div class="form-group">
                <label asp-for="Email">Email</label>
                <input type="email" asp-for="Email" id="inputDescription" class="form-control" >
              </div>
           
                <div class="form-group">
                   <input type="submit" value="Add Contact Detail" class="btn btn-success float-right">
                 </div>
              
            </div>
            </form>
            <!-- /.card-body -->
          </div>
          
          <!-- /.card -->
        </div>
   
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->